# Generated by Django 3.2 on 2023-04-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skincategory',
            options={'verbose_name_plural': 'Skin Categories'},
        ),
    ]
